from sense_hat import SenseHat
import time
import random

sense = SenseHat()

sense.show_message(":)")
sense.show_message(":)",scroll_speed=0.25)
sense.show_message(":)",scroll_speed=0.25,text_colour=[255,255,0])
sense.show_message(":)",scroll_speed=0.25,text_colour=[255,255,0],back_colour=[0,0,255])
sense.clear()

sense.show_letter("A")
time.sleep(1)
sense.show_letter("B")
time.sleep(1)
sense.show_letter("C")
time.sleep(1)
sense.show_letter("A",text_colour=[255,0,0])
time.sleep(1)
sense.show_letter("B",text_colour=[0,255,0])
time.sleep(1)
sense.show_letter("C",text_colour=[0,0,255])
time.sleep(1)
sense.show_letter("A",text_colour=[255,0,0],back_colour=[255,255,255])
time.sleep(1)
sense.show_letter("B",text_colour=[0,255,0],back_colour=[255,255,255])
time.sleep(1)
sense.show_letter("C",text_colour=[0,0,255],back_colour=[255,255,255])
time.sleep(1)
sense.clear()

r = random.randint(0,255)
g = random.randint(0,255)
b = random.randint(0,255)
sense.show_message(":)",text_colour=[r,g,b])
r = random.randint(0,255)
g = random.randint(0,255)
b = random.randint(0,255)
sense.show_letter("A",text_colour=[r,g,b])
time.sleep(1)
sense.show_letter("B",text_colour=[r,g,b])
time.sleep(1)
sense.show_letter("C",text_colour=[r,g,b])
time.sleep(1)
r = random.randint(0,255)
g = random.randint(0,255)
b = random.randint(0,255)
sense.show_letter("A",text_colour=[r,g,b])
time.sleep(1)
r = random.randint(0,255)
g = random.randint(0,255)
b = random.randint(0,255)
sense.show_letter("B",text_colour=[r,g,b])
time.sleep(1)
r = random.randint(0,255)
g = random.randint(0,255)
b = random.randint(0,255)
sense.show_letter("C",text_colour=[r,g,b])
time.sleep(1)
sense.clear()